function [slope_al,slope_be,y_axis_al,y_axis_be] = createLmd(R, M_i, Theta_u_i, d0, d1, d2, d7, setup)
    % d7
    slope7_al = -M_i*cos(Theta_u_i);
    slope7_be = -M_i*sin(Theta_u_i);
    % d2
    slope2_al = (pi/3*cos(pi/3*R) - M_i*cos(Theta_u_i));
    slope2_be = (pi/3*sin(pi/3*R) - M_i*sin(Theta_u_i));
    % d1
    slope1_al = (pi/3*cos(pi/3*(R-1)) - M_i*cos(Theta_u_i));
    slope1_be = (pi/3*sin(pi/3*(R-1)) - M_i*sin(Theta_u_i));
    % d0
    slope0_al = -M_i*cos(Theta_u_i);
    slope0_be = -M_i*sin(Theta_u_i);
    
    % definitions
    if(setup.SEQ == 127)
        % intersection y-axis
        [y_axis7_al,y_axis7_be,...
         y_axis2_al,y_axis2_be,...
         y_axis1_al,y_axis1_be,...
         y_axis0_al,y_axis0_be] = createVerr(slope7_al,slope7_be,...
                                           slope2_al,slope2_be,...
                                           slope1_al,slope1_be,...
                                           slope0_al,slope0_be, d7,d2,d1); 
                                   
        slope_al = [slope7_al; slope2_al; slope1_al; slope0_al];
        slope_be = [slope7_be; slope2_be; slope1_be; slope0_be];
        y_axis_al = [y_axis7_al; y_axis2_al; y_axis1_al; y_axis0_al];
        y_axis_be = [y_axis7_be; y_axis2_be; y_axis1_be; y_axis0_be];
    elseif(setup.SEQ == 12)
        % intersection y-axis
        [y_axis0_al,y_axis0_be,...
         y_axis1_al,y_axis1_be,...
         y_axis2_al,y_axis2_be,...
         y_axis7_al,y_axis7_be] = createVerr(slope0_al,slope0_be,...
                                           slope1_al,slope1_be,...
                                           slope2_al,slope2_be,...
                                           slope7_al,slope7_be, d0,d1,d2); 

        slope_al = [slope0_al; slope1_al; slope2_al];
        slope_be = [slope0_be; slope1_be; slope2_be];
        y_axis_al = [y_axis0_al; y_axis1_al; y_axis2_al];
        y_axis_be = [y_axis0_be; y_axis1_be; y_axis2_be];
    elseif(setup.SEQ == 721)
        % intersection y-axis
        [y_axis7_al,y_axis7_be,...
         y_axis2_al,y_axis2_be,...
         y_axis1_al,y_axis1_be,...
         y_axis0_al,y_axis0_be] = createVerr(slope7_al,slope7_be,...
                                           slope2_al,slope2_be,...
                                           slope1_al,slope1_be,...
                                           slope0_al,slope0_be, d7,d2,d1); 

        slope_al = [slope7_al; slope2_al; slope1_al; slope0_al];
        slope_be = [slope7_be; slope2_be; slope1_be; slope0_be];
        y_axis_al = [y_axis7_al; y_axis2_al; y_axis1_al; y_axis0_al];
        y_axis_be = [y_axis7_be; y_axis2_be; y_axis1_be; y_axis0_be];
    elseif(setup.SEQ == 0121)
        % intersection y-axis
        [y_axis0_al,y_axis0_be,...
         y_axis1_al,y_axis1_be,...
         y_axis2_al,y_axis2_be,...
         y_axis12_al,y_axis12_be] = createVerr(slope0_al,slope0_be,...
                                           slope1_al,slope1_be,...
                                           slope2_al,slope2_be,...
                                           slope1_al,slope1_be, d0,d1/2,d2); 

        slope_al = [slope0_al; slope1_al; slope2_al; slope1_al];
        slope_be = [slope0_be; slope1_be; slope2_be; slope1_be];
        y_axis_al = [y_axis0_al; y_axis1_al; y_axis2_al; y_axis12_al];
        y_axis_be = [y_axis0_be; y_axis1_be; y_axis2_be; y_axis12_be];
    elseif(setup.SEQ == 7212)
        % intersection y-axis
        [y_axis7_al,y_axis7_be,...
         y_axis2_al,y_axis2_be,...
         y_axis1_al,y_axis1_be,...
         y_axis22_al,y_axis22_be] = createVerr(slope7_al,slope7_be,...
                                           slope2_al,slope2_be,...
                                           slope1_al,slope1_be,...
                                           slope2_al,slope2_be, d7,d2/2,d1); 

        slope_al = [slope7_al; slope2_al; slope1_al; slope2_al];
        slope_be = [slope7_be; slope2_be; slope1_be; slope2_be];
        y_axis_al = [y_axis7_al; y_axis2_al; y_axis1_al; y_axis22_al];
        y_axis_be = [y_axis7_be; y_axis2_be; y_axis1_be; y_axis22_be];
    elseif(setup.SEQ == 1012)
        % intersection y-axis
        [y_axis1_al,y_axis1_be,...
         y_axis0_al,y_axis0_be,...
         y_axis11_al,y_axis11_be,...
         y_axis2_al,y_axis2_be] = createVerr(slope1_al,slope1_be,...
                                           slope0_al,slope0_be,...
                                           slope1_al,slope1_be,...
                                           slope2_al,slope2_be, d1/2,d0,d1/2); 

        slope_al = [slope1_al; slope0_al; slope1_al; slope2_al];
        slope_be = [slope1_be; slope0_be; slope1_be; slope2_be];
        y_axis_al = [y_axis1_al; y_axis0_al; y_axis11_al; y_axis2_al];
        y_axis_be = [y_axis1_be; y_axis0_be; y_axis11_be; y_axis2_be];
    elseif(setup.SEQ == 2721)
        % intersection y-axis
        [y_axis2_al,y_axis2_be,...
         y_axis7_al,y_axis7_be,...
         y_axis21_al,y_axis21_be,...
         y_axis1_al,y_axis1_be] = createVerr(slope2_al,slope2_be,...
                                           slope7_al,slope7_be,...
                                           slope2_al,slope2_be,...
                                           slope1_al,slope1_be, d2/2,d7,d2/2); 

        slope_al = [slope2_al; slope7_al; slope2_al; slope1_al];
        slope_be = [slope2_be; slope7_be; slope2_be; slope1_be];
        y_axis_al = [y_axis2_al; y_axis7_al; y_axis21_al; y_axis1_al];
        y_axis_be = [y_axis2_be; y_axis7_be; y_axis21_be; y_axis1_be];
    end
end